name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # ✅ Permite escribir en el repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.2"
          cache: "yarn"
          cache-dependency-path: app/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: app

      - name: Build Project
        run: yarn build
        working-directory: app

      - name: Deploy to 'build' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: app/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ✅ Se usa el token automático de GitHub
          MESSAGE: "Build: (${GITHUB_SHA})"
