name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.2"
          cache: "yarn"
          cache-dependency-path: app/yarn.lock # <-- Aquí indicamos la ubicación del lock file

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: app # <-- Instalamos en la carpeta "app"

      - name: Build Project
        run: yarn build
        working-directory: app # <-- Ejecutamos el build en "app"

      - name: Deploy to 'build' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: app/dist # <-- Aseguramos que el build esté en "app/dist"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: (${GITHUB_SHA})"
